version: '3'
services:
  shyftgeth:
    build:
      context: $PWD 
      dockerfile: ./Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30301:30301"
      - "30301:30301/udp"
      - "30303:30303"
      - "30303:30303/udp"
      - "30304:30304"
      - "31333:31333"
      - "31333:31333/udp"
      - "8081:8081"
    volumes:
      - ./shyftData/:/go-empyrean/shyftData/
      - ./shyft-config/:/go-empyrean/shyft-config/
    working_dir: /go-empyrean
    depends_on: 
      - pg
    networks:
      - shyftnet
    command: >
      sh -c 'cd /go-empyrean &&
            ./shyft-config/wait-for.sh pg:5432 &&
            DBENV=docker export DBENV &&
            ./shyft-config/shyft-cli/initShyftGeth.sh &&
            ./shyft-config/shyft-cli/startShyftGeth.sh'
  pg:
    build:
      context: $PWD
      dockerfile: docker/development/pg/Dockerfile
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    networks:
      - shyftnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
  shyft_block_api:
    image: shyftnetwork/blockexplorer_api:latest
    ports:
      - "8080:8080"
    depends_on:
      - pg
    networks:
      - shyftnet
    environment:
    - DBENV=docker
    command: ./blockx_api
  shyft_block_ui:
    image: shyftnetwork/blockexplorer_ui:latest
    ports:
    - "3000:80"
    depends_on:
    - shyft_block_api
    networks:
    - shyftnet
networks:
  shyftnet:
    driver: bridge
  

